# GenBuildInfo.cmake - regenerate build_info.h when the git state changed.
# Runs on every build via the build_info target; writes only on change so
# dependents are not recompiled needlessly.  Invoked as:
#   cmake -DSRC=<source dir> -DOUT=<output header> -P GenBuildInfo.cmake

find_package(Git QUIET)

set(BUILD_NUMBER "0")
set(BUILD_HASH   "unknown")
set(BUILD_DIRTY  "")

if(GIT_FOUND AND EXISTS "${SRC}/.git")
    execute_process(
        COMMAND ${GIT_EXECUTABLE} rev-list --count HEAD
        WORKING_DIRECTORY "${SRC}"
        OUTPUT_VARIABLE BUILD_NUMBER
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET)
    execute_process(
        COMMAND ${GIT_EXECUTABLE} rev-parse --short HEAD
        WORKING_DIRECTORY "${SRC}"
        OUTPUT_VARIABLE BUILD_HASH
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET)
    execute_process(
        COMMAND ${GIT_EXECUTABLE} diff --quiet HEAD
        WORKING_DIRECTORY "${SRC}"
        RESULT_VARIABLE _dirty
        ERROR_QUIET)
    if(NOT _dirty EQUAL 0)
        set(BUILD_DIRTY "-dirty")
    endif()
endif()

set(BUILD_ID "r${BUILD_NUMBER}-g${BUILD_HASH}${BUILD_DIRTY}")

set(CONTENT "/* Generated by cmake/GenBuildInfo.cmake - do not edit. */
#pragma once
#define PIPEASIO_BUILD_NUMBER ${BUILD_NUMBER}
#define PIPEASIO_BUILD_HASH \"${BUILD_HASH}\"
#define PIPEASIO_BUILD_DIRTY \"${BUILD_DIRTY}\"
#define PIPEASIO_BUILD_ID \"${BUILD_ID}\"
")

set(_write TRUE)
if(EXISTS "${OUT}")
    file(READ "${OUT}" _old)
    if(_old STREQUAL CONTENT)
        set(_write FALSE)
    endif()
endif()
if(_write)
    get_filename_component(_dir "${OUT}" DIRECTORY)
    file(MAKE_DIRECTORY "${_dir}")
    file(WRITE "${OUT}" "${CONTENT}")
    message(STATUS "Build id: ${BUILD_ID}")
endif()
